---
title: "Spatial comparison of four approaches"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(sf)
library(tidyverse)
library(here)
library(tmap)
```


## Load dataset 

### Load grid cells 

```{r grids}
#grids 
grids <- st_read(here("analysis/data/derived_data/spatial_hex_grid.shp"), quiet = T) %>% 
  st_transform(crs = 3414)
head(grids)
```

### Load de-identified dataset
```{r dataset}
#de-identified dataset 
df <- read_csv(here("analysis/data/derived_data/deidentified_data.csv"))
head(df)
```

### Load inferred home locations 
```{r homes}
#load inferred home locations of four approaches 
hm_apdm <- read_csv(here("analysis/data/derived_data/hm_apdm.csv")) %>% mutate(name = "APDM")
hm_freq <- read_csv(here("analysis/data/derived_data/hm_freq.csv")) %>% mutate(name = "FREQ")
hm_hmlc <- read_csv(here("analysis/data/derived_data/hm_hmlc.csv")) %>% mutate(name = "HMLC")
hm_osna <- read_csv(here("analysis/data/derived_data/hm_osna.csv")) %>% mutate(name = "OSNA")
hm_all <- bind_rows(hm_apdm, hm_freq, hm_hmlc, hm_osna)
head(hm_all)
```


### Calculate odds ratio
```{r}
cal_OR <- function(df_hm, df, grids){
  #number of users with inferred homes at each grid
  df_locals_grid <- df_hm %>% 
      group_by(home) %>% 
      summarise(n_locals_grid = n_distinct(u_id))
  
  #grids that have fewer than 5 home users 
  grids_fewer5hm <- df_locals_grid %>% 
      filter(n_locals_grid < 5) %>% 
      pull(home)
  
  #users in grids that have fewer than 5 home users 
  users_in_grids_fewer5hm <- df_hm %>% 
      filter(home %in% grids_fewer5hm) %>% 
      pull(u_id) 
  
  #remove those users from inferred home dataset 
  df_hm_updated <- df_hm %>% filter(!u_id %in% users_in_grids_fewer5hm)
  
  #number of users with inferred homes at each grid
  df_locals_grids <- df_hm_updated %>% 
    group_by(home) %>% 
    summarise(n_locals_grid = n_distinct(u_id))
  
  #remove those users from de-identified dataset 
  df_updated <- df %>% filter(!u_id %in% users_in_grids_fewer5hm)
  
  df_users_grids <- df_updated %>% 
    dplyr::select(u_id, grid_id) %>% 
    unique()
  
  #calculate Odds Ratio
  df_OR <- df_users_grids %>% 
    left_join(., (df_hm_updated %>% select(-name)), by = c("u_id" = "u_id")) %>% 
    replace(., is.na(.), 0) %>% 
    mutate(type = if_else(grid_id == home, "local", "visitor")) %>% 
    group_by(grid_id, type) %>% 
    dplyr::summarise(n_user = n_distinct(u_id)) %>% 
    spread(key = "type", value = "n_user") %>% 
    replace(., is.na(.), 0) %>% 
    ungroup() %>% 
    filter(grid_id %in% df_hm_updated$home) %>% 
    mutate(total_local = sum(local), 
           total_visitor = sum(visitor)) %>% 
    mutate(OR = (local/total_local)/(visitor/total_visitor)) 
  return(df_OR)
}
```

The calculated odds ratios are in `analysis/data/derived_data`.
```{r odds-ratio}
#APDM
if(file.exists(here("analysis/data/derived_data/OR_apdm.csv"))){
  OR_apdm <- read_csv(here("analysis/data/derived_data/OR_apdm.csv"))
} else{
  OR_apdm <- cal_OR(hm_apdm, df, grids)
  write_csv(OR_apdm, path = here("analysis/data/derived_data/OR_apdm.csv"))
}

#FREQ
if(file.exists(here("analysis/data/derived_data/OR_freq.csv"))){
  OR_freq <- read_csv(here("analysis/data/derived_data/OR_freq.csv"))
} else{
  OR_freq <- cal_OR(hm_freq, df, grids)
  write_csv(OR_freq, path = here("analysis/data/derived_data/OR_freq.csv"))
}

#HMLC
if(file.exists(here("analysis/data/derived_data/OR_hmlc.csv"))){
  OR_hmlc <- read_csv(here("analysis/data/derived_data/OR_hmlc.csv"))
} else{
  OR_hmlc <- cal_OR(hm_hmlc, df, grids)
  write_csv(OR_hmlc, path = here("analysis/data/derived_data/OR_hmlc.csv"))
}


#OSNA
if(file.exists(here("analysis/data/derived_data/OR_osna.csv"))){
  OR_osna <- read_csv(here("analysis/data/derived_data/OR_osna.csv"))
} else{
  OR_osna <- cal_OR(hm_osna, df, grids)
  write_csv(OR_osna, path = here("analysis/data/derived_data/OR_osna.csv"))
}

## convert to sf object
OR_apdm <- OR_apdm %>% left_join(., grids) %>% st_as_sf()
OR_freq <- OR_freq %>% left_join(., grids) %>% st_as_sf()
OR_hmlc <- OR_hmlc %>% left_join(., grids) %>% st_as_sf()
OR_osna <- OR_osna %>% left_join(., grids) %>% st_as_sf()
```

### Geospatial distribution of inferred home locations

```{r}
spatial_view <- function(grids, df_OR, n = 8, method_nm, breaks){
  tm_shape(grids) +
  tm_borders(col = "grey") +
  tm_shape(df_OR) +
  tm_fill("OR", 
          palette = "YlOrRd",
          style = "fixed",
          breaks = breaks,
          legend.hist = TRUE,
          title = "Odds Ratio") +
  tm_layout(title = method_nm,
            title.position = c("left", "top"),
            legend.outside = F,
            legend.position = c("right", "bottom"),
            legend.hist.height = 0.1,
            legend.hist.width = 0.3,
            legend.hist.size = 0.5)
}
```

#### APDM

```{r apdm}
spatial_view(grids, OR_apdm, method_nm = "APDM", breaks = c(0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5))
```

#### FREQ

```{r freq}
spatial_view(grids, OR_freq, method_nm = "FREQ", breaks = c(0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5))
```

#### HMLC

```{r hmlc}
spatial_view(grids, OR_hmlc, method_nm = "HMLC", breaks = c(0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5))
```

#### OSNA

```{r osna}
spatial_view(grids, OR_osna, method_nm = "OSNA", breaks = c(0, 0.3, 0.5, 1, 3, 5, 7, 9))
```




